# Generated by Django 3.0.3 on 2020-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGuide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='user_address3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_meifuri',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_seifuri',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_mei',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_sei',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
