# Generated by Django 3.0.3 on 2020-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGuide', '0002_auto_20200226_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='user_address1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_address2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_pass',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_post',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_seinen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
