# Generated by Django 3.0.3 on 2020-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGuide', '0003_auto_20200226_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='user_mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_pass',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_post',
            field=models.SlugField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_seinen',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_tel',
            field=models.SlugField(blank=True, max_length=13, null=True),
        ),
    ]
