# Generated by Django 3.0.3 on 2020-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGuide', '0006_auto_20200226_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='user_あああ',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
