# Generated by Django 3.0.3 on 2020-02-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGuide', '0007_tourist_user_あああ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_sei', models.CharField(blank=True, max_length=32, null=True)),
                ('guide_mei', models.CharField(blank=True, max_length=32, null=True)),
                ('guide_seifuri', models.CharField(blank=True, max_length=32, null=True)),
                ('guide_meifuri', models.CharField(blank=True, max_length=32, null=True)),
                ('guide_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('guide_seinen', models.DateField(blank=True, null=True, verbose_name='date published')),
                ('guide_tel', models.SlugField(blank=True, max_length=13, null=True)),
                ('guide_mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('guide_pass', models.SlugField(blank=True, max_length=20, null=True)),
                ('guide_post', models.SlugField(blank=True, max_length=8, null=True)),
                ('guide_address1', models.CharField(blank=True, max_length=10, null=True)),
                ('guide_address2', models.CharField(blank=True, max_length=32, null=True)),
                ('guide_address3', models.CharField(blank=True, max_length=64, null=True)),
                ('guide_qual', models.CharField(blank=True, max_length=500, null=True)),
                ('guide_pr', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='user_あああ',
        ),
    ]
