# Generated by Django 3.0.3 on 2020-02-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGuide', '0008_auto_20200226_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='性別名')),
            ],
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='user_sex',
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_mei',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='利用者名'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_sei',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='利用者姓'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_seinen',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appGuide.Gender', verbose_name='性別'),
        ),
    ]
