# Generated by Django 3.0.3 on 2020-02-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGuide', '0009_auto_20200226_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='guide_sex',
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appGuide.Gender', verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_address1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_address2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_address3',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='番地・建物'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_mail',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_mei',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ガイド名'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_meifuri',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ガイド名(ふりがな)'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_pass',
            field=models.SlugField(blank=True, max_length=20, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_post',
            field=models.SlugField(blank=True, max_length=8, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_pr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='PR欄'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_qual',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='保有資格'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_sei',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ガイド姓'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_seifuri',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ガイド姓(ふりがな)'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_seinen',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_tel',
            field=models.SlugField(blank=True, max_length=13, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_address1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_address2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_address3',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='番地・建物'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_mail',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_meifuri',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='利用者名(ふりがな)'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_pass',
            field=models.SlugField(blank=True, max_length=20, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_post',
            field=models.SlugField(blank=True, max_length=8, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_seifuri',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='利用者姓(ふりがな)'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_tel',
            field=models.SlugField(blank=True, max_length=13, null=True, verbose_name='電話番号'),
        ),
    ]
